nelmio_api_doc:
  documentation:
    info:
      title: Chat & Go
      description: Un chat en forma de servicio APIRest!
      version: 0.5.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
